[zsh] trap exit in tempspace

diff --git a/.zsh/functions/tempspace b/.zsh/functions/tempspace
--- a/.zsh/functions/tempspace
+++ b/.zsh/functions/tempspace
@@ -3,15 +3,17 @@ main() {
   echo 'creating temporary space...'
   local dir
   dir=$(mktemp -d -t tempspace 2>/dev/null || mktemp -d -t tempspace.XXXXXXXX)
-  [[ $status != 0 ]] && echo "$(deco -f red error): cannot create temporary space" && return 1
+  if [[ $status != 0 ]]; then
+    echo "$(deco -f red error): cannot create temporary space"
+    return 1
+  fi
 
-  # 1. trap tmux's kill-pane
-  # 2. TEMPSPACE is set as current dir name
+  # 1. trap exit, hup, and term
+  # 2. set TEMPSPACE as current dir name
   # 3. cd TEMPSPACE
   # 4. clear and show message
-  AFTER_RC="trap 'rm -rf $dir' 1; setopt auto_name_dirs; export TEMPSPACE=$dir; cd $dir; clear; border 'Entered temporary space. To exit, run \`exit\` command.'" zsh -i
+  AFTER_RC="trap 'rm -rf $dir; exit 0' EXIT HUP TERM; setopt auto_name_dirs; export TEMPSPACE=$dir; cd $dir; clear; echo 'Entered temporary space. To exit, run \`exit\` command.' | border | deco -f green" zsh -i
 
-  rm -rf "$dir"
   clear
 }
 
